### ISSUE TITLE
Mockup METZTLI

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-metztli#2]
Práctica 3. Mockup. ACTUALIZADA

[Práctica 3 Metztli Diseño de Mockup..pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-metztli/files/8559250/Practica.3.Metztli.Diseno.de.Mockup.pdf)

**Comment by Yabin-2021** [comment]
Bien  hecho 

20 %

**Comment by josealfredo79** [comment]
Para realizar una Dapp el acceso debe ser por medio de Near...porque debe ser descentralizada...
![image](https://user-images.githubusercontent.com/58342642/163250849-9a635c81-e8cc-42d3-bf7b-ea8fb6c1c5aa.png)
En una Dapp no es necesario capturar los datos del usuario...

**Comment by josealfredo79** [comment]
Las Dapps son mucho mas seguras que las App porque no almacenan los datos...por el momento solo vamos a desarrollar el puro backend. favor de corregir para que sea una Dapp..

MintbaseEs
un mercado similar a Amazon. Permite a cualquier usuario, incluidos aquellos con poco conocimiento técnico, desarrollar y distribuir sus propios bienes digitales únicos a través de su contrato inteligente. El precio típico para participar en contratos inteligentes a veces puede acercarse a los dos dígitos. Debido a estos inconvenientes, el equipo de Mintbase buscó una plataforma alternativa y descubrió near protocol.

**Comment by josealfredo79** [comment]
https://awesomenear.com/categories/dapps aqui estan ejemplos de muchas DApps

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163255299-265ae986-a93a-4da8-bbb8-3d52ee4aecec.png)
https://learnnear.club/
Favor de hacer los cambios por favor

**Comment by josealfredo79** [comment]
Para que se toma  en cuenta debe hacer los cambios por favor...
